From beevelop/ionic

MAINTAINER zhangzhuang 
RUN mkdir  /opt/apps/  && \
    cd /opt/apps  && \
    ionic start myApp01 blank && \
    ionic start myApp02 tabs  && \
    ionic start myApp03 sidemenu  && \
    cd myApp  && \
    ionic serve
